#! /usr/bin/env sh

DIR=$(dirname "$0")
cd "$DIR"

. scripts/functions.sh

# Ask for the administrator password upfront
info "Prompting for sudo password..."
if sudo -v; then
    # Keep-alive: update existing `sudo` time stamp until `setup.sh` has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
    success "Sudo credentials updated."
else
    error "Failed to obtain sudo credentials."
fi

./os/$(get_os)/setup.sh
./fish/setup.sh
./git/setup.sh
./vim/setup.sh
./vscode/setup.sh

success "Finished installing Dotfiles"
